concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "dockerized runner"
  url = "http://gitlab"
  token = "478097d855f2e001e13faf0e28aa18"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mode = "gitlab_default"
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
